window.ISLA_CLIPS = {
"ahhh": "ahhh.mp3",
"ooooh": "ooooh.mp3",
"eeee": "eeee.mp3",
"uh oh": "uh-oh.mp3",
"wheee": "wheee.mp3",
"wow": "wow.mp3",
"mmmm": "mmmm.mp3",
"shhhh": "shhhh.mp3",
"boo": "boo.mp3",
"owww": "owww.mp3",
"moooo": "moooo.mp3",
"baaa": "baaa.mp3",
"woof woof": "woof-woof.mp3",
"meow": "meow.mp3",
"oink oink": "oink-oink.mp3",
"quack quack": "quack-quack.mp3",
"hoo hoo": "hoo-hoo.mp3",
"beep beep": "beep-beep.mp3",
"choo choo": "choo-choo.mp3",
"pop": "pop-x.mp3",
"mama": "mama.mp3",
"dada": "dada.mp3",
"papa": "papa.mp3",
"nana": "nana.mp3",
"baba": "baba.mp3",
"bye bye": "bye-bye.mp3",
"night night": "night-night.mp3",
"boo boo": "boo-boo.mp3",
"num num": "num-num.mp3",
"yum yum": "yum-yum.mp3",
"more": "more.mp3",
"up": "up.mp3",
"go": "go.mp3",
"no": "no.mp3",
"hi": "hi.mp3",
"bye": "bye.mp3",
"me": "me.mp3",
"my": "my.mp3",
"eat": "eat.mp3",
"out": "out.mp3",
"on": "on.mp3",
"off": "off.mp3",
"two": "two.mp3",
"do": "do.mp3",
"bee": "bee.mp3",
"pie": "pie.mp3",
"bow": "bow.mp3",
"ball": "ball.mp3",
"baby": "baby.mp3",
"bubble": "bubble.mp3",
"bath": "bath.mp3",
"puppy": "puppy.mp3",
"mommy": "mommy.mp3",
"daddy": "daddy.mp3",
"done": "done.mp3",
"down": "down.mp3",
"nose": "nose.mp3",
"hat": "hat.mp3",
"hot": "hot.mp3",
"hug": "hug.mp3",
"wet": "wet.mp3",
"water": "water.mp3",
"walk": "walk.mp3",
"yay!": "yay-x.mp3",
"good trying!": "good-trying-x.mp3",
"nice talking!": "nice-talking-x.mp3",
"you did it!": "you-did-it-x.mp3",
"great job!": "great-job-x.mp3",
"wow!": "wow-x.mp3",
"hooray!": "hooray-x.mp3",
"yay isla!": "yay-isla-x.mp3",
"good job isla!": "good-job-isla-x.mp3",
"hi isla lets play!": "hi-isla-lets-play-x.mp3",
"hi lets play": "hi-lets-play.mp3",
"pick a picture": "pick-a-picture.mp3",
"pop!": "pop-x.mp3",
"more!": "more-x.mp3",
"more?": "more-q.mp3",
"uh oh all gone more?": "uh-oh-all-gone-more-q.mp3",
"pop the bubbles!": "pop-the-bubbles-x.mp3",
"ready": "ready.mp3",
"set": "set.mp3",
"ready set": "ready-set.mp3",
"go!": "go-x.mp3",
"ready set go!": "ready-set-go-x.mp3",
"whats in the bag?": "whats-in-the-bag-q.mp3",
"boo!": "boo-x.mp3",
"pick a song": "pick-a-song.mp3",
"pick a silly mouth": "pick-a-silly-mouth.mp3",
"bye bye horse": "bye-bye-horse.mp3",
"its a horse!": "its-a-horse-x.mp3",
"roar": "roar.mp3",
"bye bye lion": "bye-bye-lion.mp3",
"its a lion!": "its-a-lion-x.mp3",
"ooh ooh ah ah": "ooh-ooh-ah-ah.mp3",
"bye bye monkey": "bye-bye-monkey.mp3",
"its a monkey!": "its-a-monkey-x.mp3",
"peep peep": "peep-peep.mp3",
"bye bye chick": "bye-bye-chick.mp3",
"wheres bear?": "wheres-bear-q.mp3",
"theres bear!": "theres-bear-x.mp3",
"wheres baby?": "wheres-baby-q.mp3",
"theres baby!": "theres-baby-x.mp3",
"wheres grandpa?": "wheres-grandpa-q.mp3",
"theres grandpa!": "theres-grandpa-x.mp3",
"wheres grandma?": "wheres-grandma-q.mp3",
"theres grandma!": "theres-grandma-x.mp3",
"wheres monkey?": "wheres-monkey-q.mp3",
"theres monkey!": "theres-monkey-x.mp3",
"bye bye cat": "bye-bye-cat.mp3",
"its a cat!": "its-a-cat-x.mp3",
"bye bye pig": "bye-bye-pig.mp3",
"its a pig!": "its-a-pig-x.mp3",
"bye bye duck": "bye-bye-duck.mp3",
"its a duck!": "its-a-duck-x.mp3",
"bye bye owl": "bye-bye-owl.mp3",
"its an owl!": "its-an-owl-x.mp3",
"buzz": "buzz.mp3",
"bye bye bee": "bye-bye-bee.mp3",
"its a bee!": "its-a-bee-x.mp3",
"sss": "sss.mp3",
"bye bye snake": "bye-bye-snake.mp3",
"its a snake!": "its-a-snake-x.mp3",
"neigh": "neigh.mp3",
"vroooom": "vroooom.mp3",
"lets make silly mouths!": "lets-make-silly-mouths-x.mp3",
"up!": "up-x.mp3",
"uh oh down!": "uh-oh-down-x.mp3",
"down!": "down-x.mp3",
"lets build it up!": "lets-build-it-up-x.mp3",
"woo woo": "woo-woo.mp3",
"whee": "whee.mp3",
"moo": "moo.mp3",
"bye bye cow": "bye-bye-cow.mp3",
"its a cow!": "its-a-cow-x.mp3",
"baa": "baa.mp3",
"bye bye sheep": "bye-bye-sheep.mp3",
"its a sheep!": "its-a-sheep-x.mp3",
"bye bye dog": "bye-bye-dog.mp3",
"its a dog!": "its-a-dog-x.mp3",
"its a chick!": "its-a-chick-x.mp3",
"ribbit": "ribbit.mp3",
"bye bye frog": "bye-bye-frog.mp3",
"its a frog!": "its-a-frog-x.mp3",
"wheres puppy?": "wheres-puppy-q.mp3",
"theres puppy!": "theres-puppy-x.mp3",
"wheres kitty?": "wheres-kitty-q.mp3",
"theres kitty!": "theres-kitty-x.mp3",
"wheres bunny?": "wheres-bunny-q.mp3",
"theres bunny!": "theres-bunny-x.mp3",
"wheres froggy?": "wheres-froggy-q.mp3",
"theres froggy!": "theres-froggy-x.mp3",
"wheres isla?": "wheres-isla-q.mp3",
"theres isla!": "theres-isla-x.mp3",
"oh": "oh.mp3",
"with a moo moo here and a moo moo": "with-a-moo-moo-here-and-a-moo-moo.mp3",
"there": "there.mp3",
"twinkle twinkle little": "twinkle-twinkle-little.mp3",
"star": "star.mp3",
"how i wonder what you": "how-i-wonder-what-you.mp3",
"are": "are.mp3",
"up above the world so": "up-above-the-world-so.mp3",
"high": "high.mp3",
"row row row your": "row-row-row-your.mp3",
"boat": "boat.mp3",
"gently down the": "gently-down-the.mp3",
"stream": "stream.mp3",
"merrily merrily merrily merrily life is but a": "merrily-merrily-merrily-merrily-life-is-but-a.mp3",
"dream": "dream.mp3",
"the wheels on the bus go round and": "the-wheels-on-the-bus-go-round-and.mp3",
"round": "round.mp3",
"the horn on the bus goes beep beep": "the-horn-on-the-bus-goes-beep-beep.mp3",
"beep": "beep.mp3",
"the baby on the bus goes wah wah": "the-baby-on-the-bus-goes-wah-wah.mp3",
"wah": "wah.mp3",
"ring around the rosie a pocket full of posies ashes ashes we all fall": "ring-around-the-rosie-a-pocket-full-of-posies-ashes-ashes-we-all-fall.mp3",
"peekaboo i see": "peekaboo-i-see.mp3",
"you": "you.mp3",
"where is the baby peeka": "where-is-the-baby-peeka.mp3",
"mwah": "mwah.mp3",
"la la": "la-la.mp3",
"old macdonald had a farm and on that farm he had a cow and the cow says": "old-macdonald-cow.mp3",
"and on that farm he had a pig and the pig says": "old-macdonald-pig.mp3"
};
